In [3]:
!pip install numpy

In [2]:
#numpy - define arrays
import numpy as np
a = np.array([10,20,30,40,"a"])
b = np.array([10,20,30,40])
c = np.array([[10,20,30],[40,50,60]])
d = np.array([[[10,20,30],[40,50,60],[70,80,90]],[[100,110,120],[130,140,150],[160,170,180]],[[190,200,210],[220,230,240],[250,260,270]]])
e = np.array([1,2,3,4])
print(f"array {a} array length {len(a)} array type {type(a)} array datatype {a.dtype} , dimension {a.ndim} shape {a.shape}")
print(f"array {b} array length {len(b)} array type {type(b)} array datatype {b.dtype} dimension {b.ndim} shape {b.shape}")
print(f"array {c} array length {len(c)} array type {type(c)} array datatype {c.dtype} dimension {c.ndim} shape {c.shape}")
print(f"array {d} array length {len(d)} array type {type(d)} array datatype {d.dtype} dimension {d.ndim} shape {d.shape}")

#indexing
print(f"fetch 4th element in {a}: {a[2]}") #1 dimension
print(f"fetch 2nd row 2nd element in {c}: {c[1,1]}") #2 dimension
print(f"fetch 3rd layer 2nd row 1st  element in {d}: {d[2][1][0]}") #3 dimension

#slicing [start,stop,step]
print(f"fetch elements after 2nd index in {b}: {b[2:]}")
print(f"fetch elements in 2nd column in all rows {c}: {c[:,1]}")
print(f"fetch elements in 3rd column in all rows in first layer {d}: {d[0,:,2]}")
print(f"fetch elements in 2nd column in all rows in all layers {d}: {d[:,:,1]}")

#conditions
print(f" print true if the element is even in 1D {e % 2==0}")
print(f"fetch elements divisible by 3 in 2d {c[c %3 == 0]}")

array ['10' '20' '30' '40' 'a'] array length 5 array type <class 'numpy.ndarray'> array datatype <U21 , dimension 1 shape (5,)
array [10 20 30 40] array length 4 array type <class 'numpy.ndarray'> array datatype int64 dimension 1 shape (4,)
array [[10 20 30]
 [40 50 60]] array length 2 array type <class 'numpy.ndarray'> array datatype int64 dimension 2 shape (2, 3)
array [[[ 10  20  30]
  [ 40  50  60]
  [ 70  80  90]]

 [[100 110 120]
  [130 140 150]
  [160 170 180]]

 [[190 200 210]
  [220 230 240]
  [250 260 270]]] array length 3 array type <class 'numpy.ndarray'> array datatype int64 dimension 3 shape (3, 3, 3)
fetch 4th element in ['10' '20' '30' '40' 'a']: 30
fetch 2nd row 2nd element in [[10 20 30]
 [40 50 60]]: 50
fetch 3rd layer 2nd row 1st  element in [[[ 10  20  30]
  [ 40  50  60]
  [ 70  80  90]]

 [[100 110 120]
  [130 140 150]
  [160 170 180]]

 [[190 200 210]
  [220 230 240]
  [250 260 270]]]: 220
fetch elements after 2nd index in [10 20 30 40]: [30 40]
fetch elements i

In [21]:
#Create arrays using arange, eye, zeros, full, diag
#arange
print(f"*** arange ***")
a_arr = np.arange(10,20) #arange(start,stop,step)
print(a_arr)
b_arr = np.arange(10,41,2) # prints even 1D array from 10 till 40
print(b_arr)

#eye
print(f"*** eye ***")
a_eye_arr = np.eye(6,dtype = "int")
print(a_eye_arr)
b_eye_arr = np.eye(6) #default dtype is float
print(b_eye_arr)
#zeros
print(f"*** zeros ***")
a_0_arr = np.zeros((5,4),dtype ="int")
print(a_0_arr)
b_0_arr = np.zeros((4,4))
print(b_0_arr)

#one
print(f"*** one ***")
a_one_arr = np.ones((5,4),dtype ="int")
print(a_one_arr)
b_one_arr = np.ones((4,4))
print(b_one_arr)

#full
print(f"*** full ***")
a_full_arr = np.full((5,4),4,dtype ="int")
print(a_full_arr)
b_full_arr = np.full((4,4),3)
print(b_full_arr)

#diag
print(f"*** diag ***")
b_diag_list = np.arange(10,41,2)
print(b_diag_list)
b_diag_arr = np.diag(b_diag_list)
print(b_diag_arr)


*** arange ***
[10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]
*** eye ***
[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
*** zeros ***
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
*** one ***
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
*** full ***
[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]
[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]
*** diag ***
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]
[[10  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 12  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 14  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 16  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 18  0  0  0  0  0 

In [12]:
#Flatten, Ravel()
import numpy as np
#diag
print(f"*** diag ***")
b_diag_list = np.arange(10,20,2)
print(b_diag_list)
b_diag_arr = np.diag(b_diag_list)


#ravel
print(f"b_diag_arr -\n {b_diag_arr}  dimension {b_diag_arr.ndim} shape {b_diag_arr.shape}")
b_ravel_arr = b_diag_arr.ravel()
print(f"b_ravel_arr -\n {b_ravel_arr}  dimension {b_ravel_arr.ndim} shape {b_ravel_arr.shape}")
print("** updating ravel array value acts as view - modifying original array **")
b_ravel_arr[0] = 30
print(b_ravel_arr)
print(f"b_ravel_arr -\n {b_ravel_arr}  dimension {b_ravel_arr.ndim} shape {b_ravel_arr.shape}")
print(f"after ravel b_diag_arr -\n {b_diag_arr}  dimension {b_diag_arr.ndim} shape {b_diag_arr.shape}")

*** diag ***
[10 12 14 16 18]
b_diag_arr -
 [[10  0  0  0  0]
 [ 0 12  0  0  0]
 [ 0  0 14  0  0]
 [ 0  0  0 16  0]
 [ 0  0  0  0 18]]  dimension 2 shape (5, 5)
b_ravel_arr -
 [10  0  0  0  0  0 12  0  0  0  0  0 14  0  0  0  0  0 16  0  0  0  0  0
 18]  dimension 1 shape (25,)
** updating ravel array value acts as view - modifying original array **
[30  0  0  0  0  0 12  0  0  0  0  0 14  0  0  0  0  0 16  0  0  0  0  0
 18]
b_ravel_arr -
 [30  0  0  0  0  0 12  0  0  0  0  0 14  0  0  0  0  0 16  0  0  0  0  0
 18]  dimension 1 shape (25,)
after ravel b_diag_arr -
 [[30  0  0  0  0]
 [ 0 12  0  0  0]
 [ 0  0 14  0  0]
 [ 0  0  0 16  0]
 [ 0  0  0  0 18]]  dimension 2 shape (5, 5)


In [13]:
#Flatten
import numpy as np
#diag
print(f"*** diag ***")
b_diag_list = np.arange(10,20,2)
print(b_diag_list)
b_diag_arr = np.diag(b_diag_list)

print(f"b_diag_arr -\n {b_diag_arr}  dimension {b_diag_arr.ndim} shape {b_diag_arr.shape}")
b_flat_arr = b_diag_arr.flatten()
print(f"b_flat_arr -\n {b_flat_arr}  dimension {b_flat_arr.ndim} shape {b_flat_arr.shape}")
print("** updating flatten array value acts as copy and retains original array as same **")
b_flat_arr[0] = 65
print(b_flat_arr)
print(f"b_flat_arr -\n {b_flat_arr}  dimension {b_flat_arr.ndim} shape {b_flat_arr.shape}")
print(f"after ravel b_diag_arr -\n {b_diag_arr}  dimension {b_diag_arr.ndim} shape {b_diag_arr.shape}")

*** diag ***
[10 12 14 16 18]
b_diag_arr -
 [[10  0  0  0  0]
 [ 0 12  0  0  0]
 [ 0  0 14  0  0]
 [ 0  0  0 16  0]
 [ 0  0  0  0 18]]  dimension 2 shape (5, 5)
b_flat_arr -
 [10  0  0  0  0  0 12  0  0  0  0  0 14  0  0  0  0  0 16  0  0  0  0  0
 18]  dimension 1 shape (25,)
** updating flatten array value acts as copy and retains original array as same **
[65  0  0  0  0  0 12  0  0  0  0  0 14  0  0  0  0  0 16  0  0  0  0  0
 18]
b_flat_arr -
 [65  0  0  0  0  0 12  0  0  0  0  0 14  0  0  0  0  0 16  0  0  0  0  0
 18]  dimension 1 shape (25,)
after ravel b_diag_arr -
 [[10  0  0  0  0]
 [ 0 12  0  0  0]
 [ 0  0 14  0  0]
 [ 0  0  0 16  0]
 [ 0  0  0  0 18]]  dimension 2 shape (5, 5)


In [21]:
#double equal, transpose
import numpy as np
#diag
print(f"*** diag ***")
b_diag_list = np.arange(10,18,2)
print(b_diag_list)
b_diag_arr = np.diag(b_diag_list)
print(f"b_diag_arr -\n {b_diag_arr}  dimension {b_diag_arr.ndim} shape {b_diag_arr.shape}")

b_reshape_arr = b_diag_arr.reshape(8,2)
print(f"b_reshape_arr -\n {b_reshape_arr}  dimension {b_reshape_arr.ndim} shape {b_reshape_arr.shape}")

#transpose
b_transpose_arr = b_reshape_arr.transpose()

print(f"b_transpose_arr -\n {b_transpose_arr}  dimension {b_transpose_arr.ndim} shape {b_transpose_arr.shape}")


*** diag ***
[10 12 14 16]
b_diag_arr -
 [[10  0  0  0]
 [ 0 12  0  0]
 [ 0  0 14  0]
 [ 0  0  0 16]]  dimension 2 shape (4, 4)
b_reshape_arr -
 [[10  0]
 [ 0  0]
 [ 0 12]
 [ 0  0]
 [ 0  0]
 [14  0]
 [ 0  0]
 [ 0 16]]  dimension 2 shape (8, 2)
b_transpose_arr -
 [[10  0  0  0  0 14  0  0]
 [ 0  0 12  0  0  0  0 16]]  dimension 2 shape (2, 8)


In [37]:
#stacking, adding, deleting, inserting
import numpy as np
a_arr = np.arange(10,20,2)
print(f"a_arr -\n {a_arr}  dimension {a_arr.ndim} shape {a_arr.shape}")
b_arr = np.arange(11,21,2)
print(f"b_arr -\n {b_arr}  dimension {b_arr.ndim} shape {b_arr.shape}")

#hstack
ab_hstack_arr = np.hstack((a_arr,b_arr))
print(f"hstack: \n {ab_hstack_arr} dimension {ab_hstack_arr.ndim} shape {ab_hstack_arr.shape}")
#vstack
ab_vstack_arr = np.vstack((a_arr,b_arr))
print(f"vstack: \n {ab_vstack_arr} dimension {ab_vstack_arr.ndim} shape {ab_vstack_arr.shape}")

#insert
ab_insert_arr = np.insert(a_arr,2,b_arr)
print(f"insert: \n {ab_insert_arr} dimension {ab_insert_arr.ndim} shape {ab_insert_arr.shape}")

#append
ab_append_arr = np.append(a_arr,b_arr,axis=0)
print(f"append: \n {ab_append_arr} dimension {ab_append_arr.ndim} shape {ab_append_arr.shape}")

#delete
ab_delete_arr = np.delete(a_arr,3)
print(f"append: \n {ab_delete_arr} dimension {ab_delete_arr.ndim} shape {ab_delete_arr.shape}")
print(f"a_arr after delete -\n {a_arr}  dimension {a_arr.ndim} shape {a_arr.shape}")



a_arr -
 [10 12 14 16 18]  dimension 1 shape (5,)
b_arr -
 [11 13 15 17 19]  dimension 1 shape (5,)
hstack: 
 [10 12 14 16 18 11 13 15 17 19] dimension 1 shape (10,)
vstack: 
 [[10 12 14 16 18]
 [11 13 15 17 19]] dimension 2 shape (2, 5)
insert: 
 [10 12 11 13 15 17 19 14 16 18] dimension 1 shape (10,)
append: 
 [10 12 14 16 18 11 13 15 17 19] dimension 1 shape (10,)
append: 
 [10 12 14 18] dimension 1 shape (4,)
a_arr after delete -
 [10 12 14 16 18]  dimension 1 shape (5,)


In [60]:
#Math and stat functions
import numpy as np
from scipy import stats

a_arr = np.arange(10,20,2)
print(f"a_arr -\n {a_arr}  dimension {a_arr.ndim} shape {a_arr.shape}")
b_arr = np.arange(11,21,2)
print(f"b_arr -\n {b_arr}  dimension {b_arr.ndim} shape {b_arr.shape}")

#vstack
ab_vstack_arr = np.vstack((a_arr,b_arr))
print(f"vstack: \n {ab_vstack_arr} dimension {ab_vstack_arr.ndim} shape {ab_vstack_arr.shape}")

#sum of all elements
ab_sum_elem = np.sum(ab_vstack_arr)
print(f"sum of all elements in \n {ab_vstack_arr} is {ab_sum_elem}")
#sum of all rows
ab_sum_rows = np.sum(ab_vstack_arr,axis = 1)
print(f"sum of all elements in \n {ab_vstack_arr} is {ab_sum_rows}")

#sum of all columns
ab_sum_cols = np.sum(ab_vstack_arr,axis = 0)
print(f"sum of all elements in \n {ab_vstack_arr} is {ab_sum_cols}")

#mean of array
ab_mean_col = np.mean(ab_vstack_arr,axis=0)
print(f"mean of columns in \n {ab_vstack_arr} is {ab_mean_col}")
ab_mean_rows = np.mean(ab_vstack_arr,axis=1)
print(f"mean of rows in \n {ab_vstack_arr} is {ab_mean_rows}")
ab_mean_elem = np.mean(ab_vstack_arr)
print(f"mean of rows in \n {ab_vstack_arr} is {ab_mean_elem}")

#median of array
ab_median_col = np.median(ab_vstack_arr,axis=0)
print(f"median of columns in \n {ab_vstack_arr} is {ab_median_col}")
ab_median_rows = np.median(ab_vstack_arr,axis=1)
print(f"median of rows in \n {ab_vstack_arr} is {ab_median_rows}")
ab_median_elem = np.median(ab_vstack_arr)
print(f"median of rows in \n {ab_vstack_arr} is {ab_median_elem}")

#where
ab_where = np.where(ab_vstack_arr %2 != 0)
print(f"condition %2 != 0 in \n {ab_vstack_arr} is {ab_where}")

#sort
a_1D_arr = np.array([0,-98,2,8,1000,-50,-1,1,50])
srt_1d = np.sort(a_1D_arr)
print(f"a_1D_arr -\n {a_1D_arr}  dimension {a_1D_arr.ndim} shape {a_1D_arr.shape} sorted array {srt_1d} descending {srt_1d[::-1]}  ")

a_full_arr = np.full((2,5),4,dtype ="int")
print(f"{a_full_arr} dimension {a_full_arr.ndim} shape {a_full_arr.shape}")
ab_vstack_srt_arr = np.vstack((b_arr,a_full_arr))
print(f"vstack: \n {ab_vstack_srt_arr} dimension {ab_vstack_srt_arr.ndim} shape {ab_vstack_srt_arr.shape} ")
srt_2d_col = np.sort(ab_vstack_srt_arr,axis=0)
print(f"sorted \n{ab_vstack_srt_arr} on columns \n {srt_2d_col} \n descending  \n {srt_2d_col[::-1]}")
srt_2d_row = np.sort(ab_vstack_srt_arr,axis=1)
print(f"sorted \n{ab_vstack_srt_arr} on rows \n{srt_2d_row} \n descending \n {srt_2d_row[::-1]}")
srt_2d_elem = np.sort(ab_vstack_srt_arr,axis=None)
print(f"sorted \n{ab_vstack_srt_arr} on elements \n{srt_2d_elem} \n descending {srt_2d_elem[::-1]}\n")


#mode

print(f"*** full ***")
a_full_arr = np.full((5,4),4,dtype ="int")
print(f"{a_full_arr} dimension {a_full_arr.ndim} shape {a_full_arr.shape}")
b_full_arr = np.full((2,4),3)
print(f"{b_full_arr} dimension {b_full_arr.ndim} shape {b_full_arr.shape}")
#vstack
ab_full_vstack_arr = np.vstack((a_full_arr,b_full_arr))
print(f"vstack: \n {ab_full_vstack_arr} dimension {ab_full_vstack_arr.ndim} shape {ab_full_vstack_arr.shape}")
#mode
ab_full_mode = stats.mode(ab_full_vstack_arr)
print(f"mode in the array \n {ab_full_vstack_arr} is {ab_full_mode}")

a_arr -
 [10 12 14 16 18]  dimension 1 shape (5,)
b_arr -
 [11 13 15 17 19]  dimension 1 shape (5,)
vstack: 
 [[10 12 14 16 18]
 [11 13 15 17 19]] dimension 2 shape (2, 5)
sum of all elements in 
 [[10 12 14 16 18]
 [11 13 15 17 19]] is 145
sum of all elements in 
 [[10 12 14 16 18]
 [11 13 15 17 19]] is [70 75]
sum of all elements in 
 [[10 12 14 16 18]
 [11 13 15 17 19]] is [21 25 29 33 37]
mean of columns in 
 [[10 12 14 16 18]
 [11 13 15 17 19]] is [10.5 12.5 14.5 16.5 18.5]
mean of rows in 
 [[10 12 14 16 18]
 [11 13 15 17 19]] is [14. 15.]
mean of rows in 
 [[10 12 14 16 18]
 [11 13 15 17 19]] is 14.5
median of columns in 
 [[10 12 14 16 18]
 [11 13 15 17 19]] is [10.5 12.5 14.5 16.5 18.5]
median of rows in 
 [[10 12 14 16 18]
 [11 13 15 17 19]] is [14. 15.]
median of rows in 
 [[10 12 14 16 18]
 [11 13 15 17 19]] is 14.5
condition %2 != 0 in 
 [[10 12 14 16 18]
 [11 13 15 17 19]] is (array([1, 1, 1, 1, 1]), array([0, 1, 2, 3, 4]))
a_1D_arr -
 [   0  -98    2    8 1000  -50   -1 